### ISSUE TITLE
IndexOutOfRangeException when trying to download activities with zero-length LatLng

### ISSUE THREAD

**Issue by darthwalsh** [gabornemeth/StravaSharp#34]
I'm getting a new error on an existing project, when I call `client.Activities.GetAllActivitiesAfter(new DateTime(2021, 1, 28))`

```
Exception has occurred: CLR/System.IndexOutOfRangeException
Exception thrown: 'System.IndexOutOfRangeException' in System.Private.CoreLib.dll: 'Index was outside the bounds of the array.'
   at StravaSharp.LatLngConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\code\RunTheGlobe\StravaSharp\src\StravaSharp\LatLng.cs:line 54
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
...
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at RestSharp.Portable.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response)
   at RestSharp.Portable.RestResponse`1.<LoadResponse>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
...
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at StravaSharp.ActivityClient.<GetAthleteActivities>d__8.MoveNext() in C:\code\RunTheGlobe\StravaSharp\src\StravaSharp\ActivityClient.cs:line 58
```

[Strava's API docs](https://developers.strava.com/docs/reference/#api-models-LatLng) say the array should have 2 elements:

> *LatLng* \
> A collection of float objects. A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.

But I can see in the strava API response `"start_latlng": [], "end_latlng": [],` for my activities of type WeightTraining, and runs that I manually uploaded and tagged Treadmill. ([posted on the strava-api group thread](https://groups.google.com/g/strava-api/c/XanI6y2eZSA?pli=1) about it, maybe somebody knows more.

I don't see a good workaround with the existing code, but I have a small patch I'll create a PR for.

**Comment by darthwalsh** [comment]
Oh! I see PR #30 is already open for this.
